services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    
 